std = {
    max_code_line_length = 100,
    max_comment_line_length = 150,
    max_line_length = 100,
    max_string_line_length = 100,

    globals = {
        "_G",
        "Class",
        "package",
        "table",
    },

    -- std.read_globals should include only the "native" Lua-related stuff
    read_globals = {
        "arg",
        "assert",
        "debug",
        "env",
        "getmetatable",
        "ipairs",
        "json",
        "math",
        "next",
        "os",
        "pairs",
        "print",
        "rawget",
        "rawset",
        "require",
        "setmetatable",
        "string",
        "tonumber",
        "tostring",
        "type",
        "unpack",
    },
}

files["**/*.lua"] = {
    max_comment_line_length = 250,

    -- globals
    globals = {
        "AssertAddedMethodsAfter",
        "AssertAddedMethodsBefore",
        "AssertChainNil",
        "AssertGetter",
        "AssertMethodExists",
        "AssertMethodIsMissing",
        "AssertSetter",
        "ClassRegistry",
        "DebugSpy",
        "DebugSpyAssert",
        "DebugSpyAssertWasCalled",
        "DebugSpyClear",
        "DebugSpyInit",
        "DebugSpyTerm",
        "Empty",
        "KnownModIndex",
        "MockDevTools",
        "MockInventoryReplica",
        "MockPlayerDevTools",
        "MockPlayerInst",
        "MockRPCClear",
        "MockRPCInit",
        "MockRPCTerm",
        "MockTheNet",
        "MockTheSim",
        "MockWorldDevTools",
        "MockWorldInst",
        "ReturnValueFn",
        "ReturnValues",
        "ReturnValuesFn",
        "SendRPCToServer",
        "TableCount",
        "TableCountFunctions",
        "TableHasValue",
        "ToVector3",
        "Vector3",
    },
    read_globals = {
        "AllPlayers",
        "CONTROL_MOVE_DOWN",
        "CONTROL_MOVE_LEFT",
        "CONTROL_MOVE_RIGHT",
        "CONTROL_MOVE_UP",
        "DebugErrorNoCallWithoutGlobal",
        "DebugErrorNoFunction",
        "EQUIPSLOTS",
        "GetModConfigData",
        "GROUND",
        "KillThreadsWithID",
        "MODS_ROOT",
        "PREFAB_SKINS_IDS",
        "scheduler",
        "softresolvefilepath",
        "StartThread",
        "STRINGS",
        "TheInput",
        "TheNet",
        "ThePlayer",
        "TheSim",
        "TheWorld",
        "TrimString",
    },
}
