std = {
    max_code_line_length = 100,
    max_comment_line_length = 150,
    max_line_length = 100,
    max_string_line_length = 100,

    globals = {
        "_G",
        "Class",
        "package",
        "table",
    },

    -- std.read_globals should include only the "native" Lua-related stuff
    read_globals = {
        "arg",
        "assert",
        "debug",
        "env",
        "getmetatable",
        "ipairs",
        "json",
        "math",
        "next",
        "os",
        "pairs",
        "print",
        "rawget",
        "rawset",
        "require",
        "setmetatable",
        "string",
        "tonumber",
        "tostring",
        "type",
        "unpack",
    },
}

files["**/*.lua"] = {
    max_comment_line_length = 250,

    -- globals
    globals = {
        "ClassRegistry",
        "KnownModIndex",
        "SendRPCToServer",
        "ToVector3",
        "Vector3",
    },
    read_globals = {
        "ACTIONS",
        "AllPlayers",
        "AssertChainNil",
        "AssertModuleGetter",
        "AssertModuleSetter",
        "AssertReturnSelf",
        "BRANCH",
        "BufferedAction",
        "CONTROL_MOVE_DOWN",
        "CONTROL_MOVE_LEFT",
        "CONTROL_MOVE_RIGHT",
        "CONTROL_MOVE_UP",
        "Empty",
        "ENCODE_SAVES",
        "EQUIPSLOTS",
        "GetModConfigData",
        "GROUND",
        "InGamePlay",
        "KillThreadsWithID",
        "MODS_ROOT",
        "PREFAB_SKINS_IDS",
        "ReturnValueFn",
        "ReturnValuesFn",
        "RPC",
        "SavePersistentString",
        "scheduler",
        "SetDebugEntity",
        "shallowcopy",
        "softresolvefilepath",
        "StartThread",
        "STRINGS",
        "TableCount",
        "TableHasValue",
        "TheFrontEnd",
        "TheInput",
        "TheNet",
        "ThePlayer",
        "TheSim",
        "TheWorld",
        "TrackedAssert",
        "TrimString",
        "TUNING",
        "USER_HISTORY_EXPIRY_TIME",
    },
}
