project = "Mod SDK"
title = "DST Mod SDK | LDoc"
description = "dst-mod-sdk"
full_description = "Mod SDK for the game [Don\'t Starve Together](https://www.klei.com/games/dont-starve-together)." .. "\n\n" ..
    [[- **Source Code:** [https://github.com/victorpopkov/dst-mod-sdk](https://github.com/victorpopkov/dst-mod-sdk)]]

dir = "doc"
file = "./"
format = "markdown"
sort_modules = true
style = "./doc/ldoc/"
use_markdown_titles = true
